import { ArrowDownRight, ArrowRight, ArrowUpRight, ScanSearch } from 'lucide-react';
import { Link } from 'wouter';
import { useListPlans } from '@workspace/api-client-react';

export default function Home() {
  const plans = useListPlans({request:{credentials:'include'}});
  return <div className="dl-public">
    <div className="dl-container"><header className="dl-nav"><Link href="/" className="dl-logo" data-testid="link-home"><span className="dl-logo-mark"><ScanSearch size={17}/></span>deal<span style={{fontFamily:'var(--app-font-serif)',fontWeight:400}}>lens</span><span style={{color:'#759b35'}}>.</span></Link><nav className="dl-nav-links"><a href="#approach" data-testid="link-approach">The approach</a><a href="#pricing" data-testid="link-pricing">Pricing</a><Link href="/sign-in" data-testid="link-sign-in">Sign in</Link><Link href="/sign-up" className="dl-link-button" data-testid="link-sign-up">Start researching ↗</Link></nav></header></div>
    <main>
      <section className="dl-hero"><div className="dl-orbit" aria-hidden="true"/><div className="dl-container dl-hero-inner"><span className="dl-kicker">A research desk for business buyers</span><h1>Know what<br/>to <em>ask next.</em></h1><div className="dl-hero-bottom"><p>Traffic estimates are only the beginning. Turn outside signals into sharper questions for the people who know the business best.</p><Link href="/sign-up" className="dl-cta" data-testid="link-start-screening">Open your desk <ArrowUpRight size={20}/></Link></div></div></section>
      <div className="dl-container dl-ticker"><span>01 / Compare</span><span>02 / Understand</span><span>03 / Ask</span><span>04 / Verify</span></div>
      <section id="approach" className="dl-section dl-container"><div className="dl-section-head"><span className="dl-eyebrow">The job of a first pass</span><div><h2>Better context.<br/><span className="dl-serif">Better conversations.</span></h2><p>Buying a business means working through incomplete information. DealLens makes a practical starting point from directional traffic data, without dressing estimates up as certainty.</p></div></div><div className="dl-steps"><div className="dl-step"><span className="dl-eyebrow">01 / Input</span><strong>Start with the right comparison.</strong><p>Screen a target alongside a relevant peer. Keep the analysis grounded in the market you're actually considering.</p></div><div className="dl-step"><span className="dl-eyebrow">02 / Read</span><strong>See what stands out.</strong><p>Review traffic patterns, acquisition channels and geographies alongside the source period and the limits of external estimates.</p></div><div className="dl-step"><span className="dl-eyebrow">03 / Act</span><strong>Take questions to the seller.</strong><p>Bring a focused checklist to the next conversation. Ask for first-party analytics and an explanation of the business behind the numbers.</p></div></div></section>
      <section className="dl-dark-section"><div className="dl-container"><span className="dl-kicker">Evidence has edges</span><h2>Not a verdict.<br/><span>A way into the conversation.</span></h2><div className="dl-evidence"><article><span className="dl-eyebrow">What you get</span><p>A comparative brief, source-linked findings, seller questions and a place to keep your research together.</p><ArrowDownRight size={27}/></article><article><span className="dl-eyebrow">What you don't</span><p>A fraud score, an investment recommendation or a substitute for access to the seller's actual analytics.</p><ArrowDownRight size={27}/></article></div></div></section>
      <section className="dl-quote dl-container"><span className="dl-eyebrow">A useful distinction</span><div><blockquote>“The question isn't whether an estimate is perfect. It's whether it helps you ask for the right proof.”</blockquote><small>DEALLENS / THE BUYER'S RESEARCH DESK</small></div></section>
      <section id="pricing" className="dl-pricing"><div className="dl-container"><span className="dl-eyebrow">Access / plans</span><div className="dl-section-head" style={{margin:'24px 0 0'}}><span/><div><h2>Room to do<br/><span className="dl-serif">the homework.</span></h2><p>Choose the research capacity that fits your deal flow. Actual allowances and checkout availability are shown below.</p></div></div>{plans.isLoading ? <div className="desk-skeleton" aria-label="Loading plans"/> : plans.isError ? <div className="desk-alert">Plan details are unavailable right now. <button onClick={() => plans.refetch()} data-testid="button-retry-plans">Try again</button></div> : <><div className="dl-pricing-grid">{plans.data?.plans.map(plan => <article className="dl-price" key={plan.tier}><span className="dl-eyebrow">{plan.tier}</span><h3>{plan.name}</h3><div><strong>{plan.tier === 'free' ? 'Free' : plan.monthlyPrice === 0 ? 'Price pending' : plan.monthlyPriceDisplay?.trim() || 'Price shown at checkout'}</strong></div><p>{plan.screenLimit} screens and {plan.aiLimit} AI questions per billing period.</p><Link href="/sign-up" data-testid={`link-plan-${plan.tier}`}>{plan.checkoutAvailable ? 'Create account for TEST checkout' : 'View availability'} <ArrowUpRight size={17}/></Link></article>)}</div><p className="desk-note">Stripe TEST mode only. No live charge will be made.</p><p className="desk-note">{plans.data?.note}</p></>}</div></section>
      <section className="dl-dark-section"><div className="dl-container"><span className="dl-kicker">Ready to start?</span><h2>Make the next<br/><span>conversation count.</span></h2><Link href="/sign-up" className="dl-cta" data-testid="link-final-cta">Create your desk <ArrowRight size={18}/></Link></div></section>
    </main><footer className="dl-footer"><div className="dl-container"><div className="dl-footer-row"><Link href="/" className="dl-logo"><span className="dl-logo-mark"><ScanSearch size={17}/></span>deallens.</Link><nav><a href="#approach">Approach</a><a href="#pricing">Pricing</a><Link href="/sign-in">Sign in</Link></nav></div><small>© {new Date().getFullYear()} DealLens. Estimates are directional. Verify with seller-provided data.</small></div></footer>
  </div>;
}